name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Build and Publish
        run: |
          dotnet build -c Release
          dotnet pack -c Release --output ./nupkg
        working-directory: ${{ secrets.Workspace }}

      - name: Publish NuGet Package
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          DOTNET_ROOT: ${{ env.NUGET_ROOT }}
        working-directory: ${{ secrets.WORKSPACE }}